---
# tasks file for config

- name: Configure Environment Variables
  ansible.builtin.template:
    src: env.j2
    dest: "{{ deploy_dir }}/.env"
    owner: "{{ ansible_user_id }}"
    mode: '0600'
  notify: Restart PAI Service
