---
# tasks file for systemd

- name: Copy Systemd Service File
  ansible.builtin.template:
    src: pai-api.service.j2
    dest: /etc/systemd/system/pai-api.service
    mode: '0644'
  become: true
  notify: Restart PAI Service

- name: Reload Systemd Daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable and Start PAI Service
  ansible.builtin.systemd:
    name: pai-api
    enabled: yes
    state: started
  become: true
