---
- name: Deploy PAI API Bridge
  hosts: pai_nodes
  vars:
    deploy_dir: /opt/pai-api
    git_repo_url: https://github.com/yourusername/pai-api.git # Change this or use file sync
    git_branch: master
  
  roles:
    - prerequisites
    - app_deploy
    - config
    - systemd

