all:
  children:
    pai_nodes:
      hosts:
        # Example host definition
        # my_pai_instance:
        #   ansible_host: 192.168.1.x
        #   ansible_user: user
        #   pai_system_name: MyPAI
        #   pai_port: 8000
        #   pai_remote_url: "http://other-pai.local:8000"

        localhost:
          ansible_connection: local
          pai_system_name: LocalPAI
          pai_port: 8000


