all:
  children:
    pai_nodes:
      hosts:
        shale:
          ansible_host: shale.local
          ansible_user: shalegreysson
          pai_system_name: Patterson
          pai_port: 8000
          pai_remote_url: "http://grimm.local:8000"

        patterson:
          ansible_host: shale-mini.local
          ansible_user: shale
          pai_system_name: Patterson
          pai_port: 8000
          pai_remote_url: "http://grimm.local:8000"

        bob:
          ansible_connection: local
          pai_system_name: Bob
          pai_port: 8000
          pai_remote_url: "http://shale.local:8000"

